export const CUISINE_OPTIONS = [
  'Thai', 'Japanese', 'Chinese', 'Korean', 'Italian',
  'American', 'Mexican', 'Indian', 'Vietnamese', 'French',
  'Mediterranean', 'Burgers', 'Pizza', 'Seafood', 'Dessert',
  'Cafe', 'BBQ', 'Ramen', 'Sushi', 'Street Food'
];

export const DIET_TAGS = [
  'Halal', 'Vegetarian', 'Vegan', 'Gluten-free', 'Dairy-free', 'Nut-free'
];

export const DINE_OPTIONS = ['Dine-in', 'Takeaway', 'Delivery'];

export const PRICE_LEVELS = ['$', '$$', '$$$', '$$$$'];

export const SPICE_LEVELS = ['None', 'Mild', 'Medium', 'Hot'];

export const sampleRestaurants = [
  {
    id: 'sample-001-siam-spice',
    name: 'Siam Spice Garden',
    cuisineTypes: ['Thai', 'Street Food'],
    priceRange: '$$',
    location: 'Sukhumvit Soi 11',
    timeToServe: 15,
    minPeople: 1,
    maxPeople: 6,
    isOpenNow: true,
    dineOptions: ['Dine-in', 'Takeaway'],
    dietTags: ['Halal'],
    spiceLevel: 'Hot',
    rating: 4,
    lastVisitedDate: null,
    notes: 'Amazing pad thai and green curry',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-002-tokyo-ramen',
    name: 'Tokyo Ramen House',
    cuisineTypes: ['Japanese', 'Ramen'],
    priceRange: '$$',
    location: 'Thonglor',
    timeToServe: 20,
    minPeople: 1,
    maxPeople: 4,
    isOpenNow: true,
    dineOptions: ['Dine-in'],
    dietTags: [],
    spiceLevel: 'Mild',
    rating: 5,
    lastVisitedDate: null,
    notes: 'Best tonkotsu ramen in town',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: true,
  },
  {
    id: 'sample-003-burger-shake',
    name: 'Burger & Shake Co.',
    cuisineTypes: ['Burgers', 'American'],
    priceRange: '$',
    location: 'Silom',
    timeToServe: 10,
    minPeople: 1,
    maxPeople: 8,
    isOpenNow: true,
    dineOptions: ['Dine-in', 'Takeaway', 'Delivery'],
    dietTags: [],
    spiceLevel: 'None',
    rating: 3,
    lastVisitedDate: null,
    notes: 'Quick and tasty burgers',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-004-bella-italia',
    name: 'Bella Italia',
    cuisineTypes: ['Italian', 'Pizza'],
    priceRange: '$$$',
    location: 'Asoke',
    timeToServe: 25,
    minPeople: 2,
    maxPeople: 10,
    isOpenNow: true,
    dineOptions: ['Dine-in', 'Delivery'],
    dietTags: ['Vegetarian'],
    spiceLevel: 'None',
    rating: 4,
    lastVisitedDate: null,
    notes: 'Authentic wood-fired pizza and pasta',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: true,
  },
  {
    id: 'sample-005-seoul-kitchen',
    name: 'Seoul Kitchen',
    cuisineTypes: ['Korean', 'BBQ'],
    priceRange: '$$',
    location: 'Phrom Phong',
    timeToServe: 30,
    minPeople: 2,
    maxPeople: 8,
    isOpenNow: false,
    dineOptions: ['Dine-in'],
    dietTags: [],
    spiceLevel: 'Medium',
    rating: 4,
    lastVisitedDate: null,
    notes: 'Great Korean BBQ with unlimited side dishes',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-006-pho-hanoi',
    name: 'Pho Hanoi',
    cuisineTypes: ['Vietnamese'],
    priceRange: '$',
    location: 'Ari',
    timeToServe: 10,
    minPeople: 1,
    maxPeople: 4,
    isOpenNow: true,
    dineOptions: ['Dine-in', 'Takeaway'],
    dietTags: ['Gluten-free'],
    spiceLevel: 'Mild',
    rating: 4,
    lastVisitedDate: null,
    notes: 'Authentic Vietnamese pho',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-007-bombay-palace',
    name: 'Bombay Palace',
    cuisineTypes: ['Indian'],
    priceRange: '$$',
    location: 'Siam',
    timeToServe: 20,
    minPeople: 2,
    maxPeople: 6,
    isOpenNow: true,
    dineOptions: ['Dine-in', 'Delivery'],
    dietTags: ['Halal', 'Vegetarian'],
    spiceLevel: 'Hot',
    rating: 5,
    lastVisitedDate: null,
    notes: 'Rich curries and fresh naan bread',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: true,
  },
  {
    id: 'sample-008-le-petit',
    name: 'Le Petit Bistro',
    cuisineTypes: ['French', 'Mediterranean'],
    priceRange: '$$$$',
    location: 'Sathorn',
    timeToServe: 40,
    minPeople: 2,
    maxPeople: 4,
    isOpenNow: false,
    dineOptions: ['Dine-in'],
    dietTags: [],
    spiceLevel: 'None',
    rating: 5,
    lastVisitedDate: null,
    notes: 'Fine dining experience, great wine list',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-009-taco-loco',
    name: 'Taco Loco',
    cuisineTypes: ['Mexican'],
    priceRange: '$',
    location: 'Ekkamai',
    timeToServe: 8,
    minPeople: 1,
    maxPeople: 6,
    isOpenNow: true,
    dineOptions: ['Dine-in', 'Takeaway', 'Delivery'],
    dietTags: ['Vegetarian'],
    spiceLevel: 'Medium',
    rating: 3,
    lastVisitedDate: null,
    notes: 'Fun casual Mexican street food',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-010-dragon-palace',
    name: 'Dragon Palace',
    cuisineTypes: ['Chinese', 'Seafood'],
    priceRange: '$$$',
    location: 'Chinatown',
    timeToServe: 25,
    minPeople: 4,
    maxPeople: 12,
    isOpenNow: true,
    dineOptions: ['Dine-in'],
    dietTags: [],
    spiceLevel: 'Medium',
    rating: 4,
    lastVisitedDate: null,
    notes: 'Perfect for large group dim sum',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-011-matcha-cafe',
    name: 'Sweet Matcha Cafe',
    cuisineTypes: ['Cafe', 'Dessert', 'Japanese'],
    priceRange: '$$',
    location: 'Siam Square',
    timeToServe: 10,
    minPeople: 1,
    maxPeople: 4,
    isOpenNow: true,
    dineOptions: ['Dine-in', 'Takeaway'],
    dietTags: ['Vegetarian'],
    spiceLevel: 'None',
    rating: 4,
    lastVisitedDate: null,
    notes: 'Instagrammable matcha desserts',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: true,
  },
  {
    id: 'sample-012-sushi-dai',
    name: 'Sushi Dai',
    cuisineTypes: ['Sushi', 'Japanese'],
    priceRange: '$$$',
    location: 'Langsuan',
    timeToServe: 20,
    minPeople: 1,
    maxPeople: 4,
    isOpenNow: true,
    dineOptions: ['Dine-in'],
    dietTags: ['Gluten-free'],
    spiceLevel: 'None',
    rating: 5,
    lastVisitedDate: null,
    notes: 'Omakase style, fresh fish daily',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
];
