export const CUISINE_OPTIONS = [
  'Thai', 'Japanese', 'Chinese', 'Korean', 'Italian',
  'American', 'Mexican', 'Indian', 'Vietnamese', 'French',
  'Mediterranean', 'Burgers', 'Pizza', 'Seafood', 'Dessert',
  'Cafe', 'BBQ', 'Ramen', 'Sushi', 'Street Food',
  'Noodles', 'Suki', 'Pasta', 'Chicken Rice',
];

export const DINE_OPTIONS = ['Dine-in', 'Takeaway', 'Delivery'];

export const sampleRestaurants = [
  {
    id: 'sample-001-siam-spice',
    name: 'Siam Spice Garden',
    cuisineTypes: ['Thai', 'Street Food'],
    priceRange: '80-150',
    location: 'Sukhumvit Soi 11',
    timeToServe: 15,
    minPeople: 1,
    maxPeople: 6,
    openHours: '10:00-22:00',
    dineOptions: ['Dine-in', 'Takeaway'],
    rating: 4.0,
    lastVisitedDate: null,
    notes: 'Amazing pad thai and green curry',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-002-tokyo-ramen',
    name: 'Tokyo Ramen House',
    cuisineTypes: ['Japanese', 'Ramen'],
    priceRange: '120-200',
    location: 'Thonglor',
    timeToServe: 20,
    minPeople: 1,
    maxPeople: 4,
    openHours: '11:00-21:00',
    dineOptions: ['Dine-in'],
    rating: 4.8,
    lastVisitedDate: null,
    notes: 'Best tonkotsu ramen in town',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: true,
  },
  {
    id: 'sample-003-burger-shake',
    name: 'Burger & Shake Co.',
    cuisineTypes: ['Burgers', 'American'],
    priceRange: '60-120',
    location: 'Silom',
    timeToServe: 10,
    minPeople: 1,
    maxPeople: 8,
    openHours: '10:00-23:00',
    dineOptions: ['Dine-in', 'Takeaway', 'Delivery'],
    rating: 3.5,
    lastVisitedDate: null,
    notes: 'Quick and tasty burgers',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-004-bella-italia',
    name: 'Bella Italia',
    cuisineTypes: ['Italian', 'Pizza'],
    priceRange: '180-350',
    location: 'Asoke',
    timeToServe: 25,
    minPeople: 2,
    maxPeople: 10,
    openHours: '11:30-22:30',
    dineOptions: ['Dine-in', 'Delivery'],
    rating: 4.3,
    lastVisitedDate: null,
    notes: 'Authentic wood-fired pizza and pasta',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: true,
  },
  {
    id: 'sample-005-seoul-kitchen',
    name: 'Seoul Kitchen',
    cuisineTypes: ['Korean', 'BBQ'],
    priceRange: '150-250',
    location: 'Phrom Phong',
    timeToServe: 30,
    minPeople: 2,
    maxPeople: 8,
    openHours: '17:00-23:00',
    dineOptions: ['Dine-in'],
    rating: 4.1,
    lastVisitedDate: null,
    notes: 'Great Korean BBQ with unlimited side dishes',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-006-pho-hanoi',
    name: 'Pho Hanoi',
    cuisineTypes: ['Vietnamese'],
    priceRange: '50-90',
    location: 'Ari',
    timeToServe: 10,
    minPeople: 1,
    maxPeople: 4,
    openHours: '08:00-20:00',
    dineOptions: ['Dine-in', 'Takeaway'],
    rating: 4.4,
    lastVisitedDate: null,
    notes: 'Authentic Vietnamese pho',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-007-bombay-palace',
    name: 'Bombay Palace',
    cuisineTypes: ['Indian'],
    priceRange: '100-200',
    location: 'Siam',
    timeToServe: 20,
    minPeople: 2,
    maxPeople: 6,
    openHours: '11:00-22:00',
    dineOptions: ['Dine-in', 'Delivery'],
    rating: 4.6,
    lastVisitedDate: null,
    notes: 'Rich curries and fresh naan bread',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: true,
  },
  {
    id: 'sample-008-le-petit',
    name: 'Le Petit Bistro',
    cuisineTypes: ['French', 'Mediterranean'],
    priceRange: '300-600',
    location: 'Sathorn',
    timeToServe: 40,
    minPeople: 2,
    maxPeople: 4,
    openHours: '18:00-23:00',
    dineOptions: ['Dine-in'],
    rating: 4.9,
    lastVisitedDate: null,
    notes: 'Fine dining experience, great wine list',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-009-taco-loco',
    name: 'Taco Loco',
    cuisineTypes: ['Mexican'],
    priceRange: '50-100',
    location: 'Ekkamai',
    timeToServe: 8,
    minPeople: 1,
    maxPeople: 6,
    openHours: '10:00-22:00',
    dineOptions: ['Dine-in', 'Takeaway', 'Delivery'],
    rating: 3.8,
    lastVisitedDate: null,
    notes: 'Fun casual Mexican street food',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-010-dragon-palace',
    name: 'Dragon Palace',
    cuisineTypes: ['Chinese', 'Seafood'],
    priceRange: '150-350',
    location: 'Chinatown',
    timeToServe: 25,
    minPeople: 4,
    maxPeople: 12,
    openHours: '10:00-21:30',
    dineOptions: ['Dine-in'],
    rating: 4.2,
    lastVisitedDate: null,
    notes: 'Perfect for large group dim sum',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
  {
    id: 'sample-011-matcha-cafe',
    name: 'Sweet Matcha Cafe',
    cuisineTypes: ['Cafe', 'Dessert', 'Japanese'],
    priceRange: '80-180',
    location: 'Siam Square',
    timeToServe: 10,
    minPeople: 1,
    maxPeople: 4,
    openHours: '09:00-21:00',
    dineOptions: ['Dine-in', 'Takeaway'],
    rating: 4.3,
    lastVisitedDate: null,
    notes: 'Instagrammable matcha desserts',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: true,
  },
  {
    id: 'sample-012-sushi-dai',
    name: 'Sushi Dai',
    cuisineTypes: ['Sushi', 'Japanese'],
    priceRange: '200-500',
    location: 'Langsuan',
    timeToServe: 20,
    minPeople: 1,
    maxPeople: 4,
    openHours: '11:30-21:30',
    dineOptions: ['Dine-in'],
    rating: 4.7,
    lastVisitedDate: null,
    notes: 'Omakase style, fresh fish daily',
    linkGoogleMaps: '',
    websiteLink: '',
    imageUrl: '',
    isFavorite: false,
  },
];
